### ISSUE TITLE
broken toppings

### ISSUE THREAD

**Issue by aimjel** [mcdevs/Burger#40]
Using packet-instructions topping in version 1.20.1 and 1.20.2 causes an error.

```
Failed to run <class 'burger.toppings.identify.IdentifyTopping'>
Traceback (most recent call last):
  File "C:\Users\angel\Desktop\burger\Burger-master\munch.py", line 252, in <module>
    topping.act(aggregate, classloader, verbose)
  File "C:\Users\angel\Desktop\burger\Burger-master\burger\toppings\identify.py", line 307, in act
    raise Exception(
Exception: Already registered enumfacing.plane to esk$b! Can't overwrite it with esw
Dependencies failed for <class 'burger.toppings.packets.PacketsTopping'>: Missing ['identify.packet.connectionstate', 'identify.packet.packetbuffer']
Dependencies failed for <class 'burger.toppings.packetinstructions.PacketInstructionsTopping'>: Missing ['packets.classes', 'identify.packet.packetbuffer', 'identify.nbtcompound', 'identify.itemstack', 'identify.chatcomponent', 'identify.metadata', 'identify.resourcelocation']
```

**Comment by TkTech** [comment]
@Pokechu22's downstream https://github.com/Pokechu22/Burger should work with these versions. It's been awhile since this repository was synced with his changes.

**Comment by aimjel** [comment]
Thank you!
